name: skill-tree
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.20
  - dash=4.1.0
  - dash-bootstrap-components=2.0.4
  - networkx=3.4.2
  - numpy=2.2.6
  - plotly=6.6.0
  - pytest=9.0.3
  - scipy=1.15.2
  - pip
  - pip:
    - dash-cytoscape==1.0.2
